"""Child-friendly animal knowledge base for Mystery Animal.

The database intentionally uses broad, familiar animals and observable traits.
It avoids technical facts a five- to seven-year-old may not know.
"""

ANIMALS = {
    "dog": dict(habitat="land", size="medium", covering="fur", legs="four", wings=False, movement={"walk", "run"}, setting={"pet"}, tail=True, shell=False, water=False),
    "cat": dict(habitat="land", size="small", covering="fur", legs="four", wings=False, movement={"walk", "climb"}, setting={"pet"}, tail=True, shell=False, water=False),
    "rabbit": dict(habitat="land", size="small", covering="fur", legs="four", wings=False, movement={"hop"}, setting={"pet", "wild"}, tail=True, shell=False, water=False),
    "hamster": dict(habitat="land", size="tiny", covering="fur", legs="four", wings=False, movement={"walk"}, setting={"pet"}, tail=False, shell=False, water=False),
    "mouse": dict(habitat="land", size="tiny", covering="fur", legs="four", wings=False, movement={"walk"}, setting={"wild", "pet"}, tail=True, shell=False, water=False),
    "squirrel": dict(habitat="land", size="small", covering="fur", legs="four", wings=False, movement={"climb", "jump"}, setting={"wild"}, tail=True, shell=False, water=False),
    "horse": dict(habitat="land", size="large", covering="hair", legs="four", wings=False, movement={"walk", "run"}, setting={"farm"}, tail=True, shell=False, water=False),
    "cow": dict(habitat="land", size="large", covering="hair", legs="four", wings=False, movement={"walk"}, setting={"farm"}, tail=True, shell=False, water=False),
    "pig": dict(habitat="land", size="medium", covering="hair", legs="four", wings=False, movement={"walk"}, setting={"farm"}, tail=True, shell=False, water=False),
    "sheep": dict(habitat="land", size="medium", covering="wool", legs="four", wings=False, movement={"walk"}, setting={"farm"}, tail=True, shell=False, water=False),
    "goat": dict(habitat="land", size="medium", covering="hair", legs="four", wings=False, movement={"walk", "climb"}, setting={"farm"}, tail=True, shell=False, water=False),
    "chicken": dict(habitat="land", size="small", covering="feathers", legs="two", wings=True, movement={"walk"}, setting={"farm"}, tail=True, shell=False, water=False),
    "duck": dict(habitat="both", size="small", covering="feathers", legs="two", wings=True, movement={"walk", "swim", "fly"}, setting={"farm", "wild"}, tail=True, shell=False, water=True),
    "goose": dict(habitat="both", size="medium", covering="feathers", legs="two", wings=True, movement={"walk", "swim", "fly"}, setting={"farm", "wild"}, tail=True, shell=False, water=True),
    "bird": dict(habitat="land", size="tiny", covering="feathers", legs="two", wings=True, movement={"fly"}, setting={"wild", "pet"}, tail=True, shell=False, water=False),
    "owl": dict(habitat="land", size="small", covering="feathers", legs="two", wings=True, movement={"fly"}, setting={"wild"}, tail=True, shell=False, water=False, time="night"),
    "eagle": dict(habitat="land", size="medium", covering="feathers", legs="two", wings=True, movement={"fly"}, setting={"wild"}, tail=True, shell=False, water=False),
    "penguin": dict(habitat="both", size="medium", covering="feathers", legs="two", wings=True, movement={"walk", "swim"}, setting={"wild"}, tail=True, shell=False, water=True),
    "flamingo": dict(habitat="both", size="medium", covering="feathers", legs="two", wings=True, movement={"walk", "fly"}, setting={"wild"}, tail=True, shell=False, water=True),
    "ostrich": dict(habitat="land", size="large", covering="feathers", legs="two", wings=True, movement={"walk", "run"}, setting={"wild"}, tail=True, shell=False, water=False),
    "lion": dict(habitat="land", size="large", covering="fur", legs="four", wings=False, movement={"walk", "run"}, setting={"wild"}, tail=True, shell=False, water=False),
    "tiger": dict(habitat="land", size="large", covering="fur", legs="four", wings=False, movement={"walk", "run", "swim"}, setting={"wild"}, tail=True, shell=False, water=False),
    "bear": dict(habitat="land", size="large", covering="fur", legs="four", wings=False, movement={"walk", "climb", "swim"}, setting={"wild"}, tail=False, shell=False, water=False),
    "panda": dict(habitat="land", size="large", covering="fur", legs="four", wings=False, movement={"walk", "climb"}, setting={"wild"}, tail=False, shell=False, water=False),
    "elephant": dict(habitat="land", size="huge", covering="skin", legs="four", wings=False, movement={"walk"}, setting={"wild"}, tail=True, shell=False, water=False),
    "giraffe": dict(habitat="land", size="huge", covering="hair", legs="four", wings=False, movement={"walk", "run"}, setting={"wild"}, tail=True, shell=False, water=False),
    "zebra": dict(habitat="land", size="large", covering="hair", legs="four", wings=False, movement={"walk", "run"}, setting={"wild"}, tail=True, shell=False, water=False),
    "monkey": dict(habitat="land", size="medium", covering="fur", legs="four", wings=False, movement={"climb", "swing", "walk"}, setting={"wild"}, tail=True, shell=False, water=False),
    "gorilla": dict(habitat="land", size="large", covering="fur", legs="four", wings=False, movement={"walk", "climb"}, setting={"wild"}, tail=False, shell=False, water=False),
    "kangaroo": dict(habitat="land", size="large", covering="fur", legs="two", wings=False, movement={"hop"}, setting={"wild"}, tail=True, shell=False, water=False),
    "deer": dict(habitat="land", size="large", covering="hair", legs="four", wings=False, movement={"walk", "run"}, setting={"wild"}, tail=True, shell=False, water=False),
    "fox": dict(habitat="land", size="medium", covering="fur", legs="four", wings=False, movement={"walk", "run"}, setting={"wild"}, tail=True, shell=False, water=False),
    "wolf": dict(habitat="land", size="large", covering="fur", legs="four", wings=False, movement={"walk", "run"}, setting={"wild"}, tail=True, shell=False, water=False),
    "raccoon": dict(habitat="land", size="medium", covering="fur", legs="four", wings=False, movement={"walk", "climb"}, setting={"wild"}, tail=True, shell=False, water=False, time="night"),
    "sloth": dict(habitat="land", size="medium", covering="fur", legs="four", wings=False, movement={"climb"}, setting={"wild"}, tail=False, shell=False, water=False),
    "hedgehog": dict(habitat="land", size="small", covering="spikes", legs="four", wings=False, movement={"walk"}, setting={"wild", "pet"}, tail=False, shell=False, water=False),
    "bat": dict(habitat="land", size="small", covering="fur", legs="two", wings=True, movement={"fly"}, setting={"wild"}, tail=False, shell=False, water=False, time="night"),
    "frog": dict(habitat="both", size="tiny", covering="skin", legs="four", wings=False, movement={"hop", "swim"}, setting={"wild"}, tail=False, shell=False, water=True),
    "turtle": dict(habitat="both", size="small", covering="scales", legs="four", wings=False, movement={"walk", "swim"}, setting={"wild", "pet"}, tail=True, shell=True, water=True),
    "crocodile": dict(habitat="both", size="large", covering="scales", legs="four", wings=False, movement={"crawl", "swim"}, setting={"wild"}, tail=True, shell=False, water=True),
    "alligator": dict(habitat="both", size="large", covering="scales", legs="four", wings=False, movement={"crawl", "swim"}, setting={"wild"}, tail=True, shell=False, water=True),
    "lizard": dict(habitat="land", size="small", covering="scales", legs="four", wings=False, movement={"crawl", "climb"}, setting={"wild", "pet"}, tail=True, shell=False, water=False),
    "snake": dict(habitat="land", size="medium", covering="scales", legs="zero", wings=False, movement={"slither"}, setting={"wild", "pet"}, tail=True, shell=False, water=False),
    "fish": dict(habitat="water", size="small", covering="scales", legs="zero", wings=False, movement={"swim"}, setting={"wild", "pet"}, tail=True, shell=False, water=True),
    "shark": dict(habitat="water", size="large", covering="skin", legs="zero", wings=False, movement={"swim"}, setting={"wild"}, tail=True, shell=False, water=True),
    "dolphin": dict(habitat="water", size="large", covering="skin", legs="zero", wings=False, movement={"swim"}, setting={"wild"}, tail=True, shell=False, water=True),
    "whale": dict(habitat="water", size="huge", covering="skin", legs="zero", wings=False, movement={"swim"}, setting={"wild"}, tail=True, shell=False, water=True),
    "seal": dict(habitat="both", size="large", covering="fur", legs="zero", wings=False, movement={"swim", "crawl"}, setting={"wild"}, tail=True, shell=False, water=True),
    "octopus": dict(habitat="water", size="medium", covering="skin", legs="eight", wings=False, movement={"swim", "crawl"}, setting={"wild"}, tail=False, shell=False, water=True),
    "squid": dict(habitat="water", size="medium", covering="skin", legs="many", wings=False, movement={"swim"}, setting={"wild"}, tail=False, shell=False, water=True),
    "jellyfish": dict(habitat="water", size="medium", covering="skin", legs="many", wings=False, movement={"float"}, setting={"wild"}, tail=False, shell=False, water=True),
    "crab": dict(habitat="both", size="small", covering="shell", legs="many", wings=False, movement={"crawl", "swim"}, setting={"wild"}, tail=False, shell=True, water=True),
    "lobster": dict(habitat="water", size="medium", covering="shell", legs="many", wings=False, movement={"crawl", "swim"}, setting={"wild"}, tail=True, shell=True, water=True),
    "starfish": dict(habitat="water", size="small", covering="skin", legs="many", wings=False, movement={"crawl"}, setting={"wild"}, tail=False, shell=False, water=True),
    "snail": dict(habitat="land", size="tiny", covering="skin", legs="zero", wings=False, movement={"crawl"}, setting={"wild", "pet"}, tail=False, shell=True, water=False),
    "worm": dict(habitat="land", size="tiny", covering="skin", legs="zero", wings=False, movement={"crawl"}, setting={"wild"}, tail=False, shell=False, water=False),
    "spider": dict(habitat="land", size="tiny", covering="skin", legs="eight", wings=False, movement={"crawl", "climb"}, setting={"wild", "pet"}, tail=False, shell=False, water=False),
    "ant": dict(habitat="land", size="tiny", covering="shell", legs="six", wings=False, movement={"crawl"}, setting={"wild"}, tail=False, shell=False, water=False),
    "bee": dict(habitat="land", size="tiny", covering="hair", legs="six", wings=True, movement={"fly"}, setting={"wild"}, tail=False, shell=False, water=False),
    "butterfly": dict(habitat="land", size="tiny", covering="scales", legs="six", wings=True, movement={"fly"}, setting={"wild"}, tail=False, shell=False, water=False),
    "ladybug": dict(habitat="land", size="tiny", covering="shell", legs="six", wings=True, movement={"fly", "crawl"}, setting={"wild"}, tail=False, shell=False, water=False),
    "grasshopper": dict(habitat="land", size="tiny", covering="shell", legs="six", wings=True, movement={"jump", "fly"}, setting={"wild"}, tail=False, shell=False, water=False),
    "centipede": dict(habitat="land", size="tiny", covering="shell", legs="many", wings=False, movement={"crawl"}, setting={"wild"}, tail=False, shell=False, water=False),
    "scorpion": dict(habitat="land", size="tiny", covering="shell", legs="eight", wings=False, movement={"crawl"}, setting={"wild"}, tail=True, shell=False, water=False),
}

COMMON_GUESSES = tuple(ANIMALS.keys())
